practica_final_orm_django/config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('laboratorio/', include(('laboratorio.urls', 'laboratorio'), namespace='laboratorio')),
    path('', views.index, name='index'),
]

practica_final_orm_django/config/laboratorio/urls.py
from django.urls import path
from . import views

app_name = 'laboratorio'

urlpatterns = [
    path('', views.listar_laboratorios, name='listar_laboratorios'),
    path('agregar/', views.agregar_laboratorio, name='agregar_laboratorio'),
    path('editar/<int:pk>/', views.editar_laboratorio, name='editar_laboratorio'),
    path('eliminar/<int:pk>/', views.eliminar_laboratorio, name='eliminar_laboratorio'),
]

practica_final_orm_django/config/laboratorio/models.py
import datetime
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Laboratorio(models.Model):
    nombre = models.CharField(max_length=200)
    ciudad =models.CharField(max_length=100, default='')
    pais = models.CharField(max_length=100, default='')
    
    def __str__(self):
        return self.nombre
    
class DirectorGeneral(models.Model):
    nombre = models.CharField(max_length=200)
    laboratorio=models.OneToOneField(Laboratorio, on_delete=models.CASCADE)
    especialidad = models.CharField(max_length=100, default='General')
    
    def __str__(self):
        return f' El {self.nombre} pertenece a: {self.laboratorio}'
    
class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    laboratorio=models.ForeignKey(Laboratorio, on_delete=models.CASCADE)
    f_fabricacion=models.DateField(validators=[MinValueValidator(datetime.date(2015,1,1))], verbose_name="F Fabricacion")
    p_costo=models.DecimalField(max_digits=10, decimal_places=2)
    p_venta=models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return f' El {self.nombre} pertenece al {self.laboratorio} con fecha de fabricacion: {self.f_fabricacion}, con costo de:$ {self.p_costo} y precio de venta: $ {self.p_venta}'
    
    

practica_final_orm_django/config/laboratorio/forms.py
from django import forms
from .models import Laboratorio

class LaboratorioForm(forms.ModelForm):
    class Meta:
        model = Laboratorio
        fields = ['nombre', 'ciudad', 'pais']  
        labels = {  # Etiquetas personalizadas para los campos
            'nombre': 'Nombre',
            'ciudad': 'Ciudad',
            'pais': 'País',
        }
        widgets = {  # Widgets personalizados para modificar apariencia o comportamiento
            'nombre': forms.TextInput(attrs={'placeholder': 'Ingrese el Nombre del laboratorio'}),
            'ciudad': forms.TextInput(attrs={'placeholder': 'Ingrese la Ciudad del laboratorio'}),
            'pais': forms.TextInput(attrs={'placeholder': 'Ingrese el Pais del laboratorio'}),
        }

practica_final_orm_django/config/config/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')#renderiza la plantilla index.html

practica_final_orm_django/config/laboratorio/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Laboratorio
from .forms import LaboratorioForm

def listar_laboratorios(request):
    laboratorios = Laboratorio.objects.all()
    return render(request, 'laboratorio/listar_laboratorios.html', {'laboratorios': laboratorios})

def agregar_laboratorio(request):
    if request.method == 'POST':
        form = LaboratorioForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('laboratorio:listar_laboratorios')
    else:
        form = LaboratorioForm()
    return render(request, 'laboratorio/agregar_laboratorio.html', {'form': form})

def editar_laboratorio(request, pk):
    laboratorio = get_object_or_404(Laboratorio, pk=pk)
    if request.method == 'POST':
        form = LaboratorioForm(request.POST, instance=laboratorio)
        if form.is_valid():
            form.save()
            return redirect('laboratorio:listar_laboratorios')
    else:
        form = LaboratorioForm(instance=laboratorio)
    return render(request, 'laboratorio/agregar_laboratorio.html', {'form': form})

def eliminar_laboratorio(request, pk):
    laboratorio = get_object_or_404(Laboratorio, pk=pk)
    if request.method == 'POST':
        laboratorio.delete()
        return redirect('laboratorio:listar_laboratorios')
    return render(request, 'laboratorio/eliminar_laboratorio.html', {'laboratorio': laboratorio})

practica_final_orm_django/config/laboratorio/templates/laboratorio/agregar_laboratorio.html
{% extends 'base.html'%}

{% load widget_tweaks %}
{% block title %} AGREGAR LABORATORIO {% endblock %}

{% block content %}
<div class="container">
    <h2 class="text-center">
    {% if form.instance.pk %} Actualizar {% else %} Ingresar los Datos del {% endif %} Laboratorio 
    </h2>

    <form method="post">
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-12 col-md-8">
                <!-- Iterar sobre los campos del formulario -->
                {% for field in form %}
                    <div class="mb-3">
                        <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                        {{ field|add_class:"form-control" }}
                    </div>
                {% endfor %}
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

practica_final_orm_django/config/laboratorio/templates/laboratorio/eliminar_laboratorio.html
{% extends 'base.html' %}

{% block title %} ELIMINAR LABORATORIO {% endblock %}

{% block content %}
    <h2>¿Estás seguro que deseas eliminar el laboratorio: "{{laboratorio.nombre}}"?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn bg-danger">Confirmar</button>
    </form>
<br>
<a href="{% url 'laboratorio:listar_laboratorios'%}" class=" btn bg-warning"> Retornar</a>

{% endblock %}

practica_final_orm_django/config/laboratorio/templates/laboratorio/listar_laboratorios.html
{% extends 'base.html'%}

{% block title %} VER LABORATORIOS {% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="text-center">Información de Laboratorios</h2>
    {% if laboratorios %}
    <div class="table-responsive mt-3">
        <table class="table table-bordered table-hover text-center">
            <thead class="table-light">
                <tr>
                    <th>Nombre</th>
                    <th>Ciudad</th>
                    <th>Pais</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for laboratorio in laboratorios %}
                <tr>
                    <td>{{ laboratorio.nombre }}</td>
                    <td>{{ laboratorio.ciudad }}</td>
                    <td>{{ laboratorio.pais }}</td>
                    <td><a href="{% url 'laboratorio:editar_laboratorio' laboratorio.pk %}" class="btn btn-light btn">Actualizar</a></td>
                    <td><a href="{% url 'laboratorio:eliminar_laboratorio' laboratorio.pk %}" class="btn btn-light btn">Eliminar</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="5">No hay laboratorios disponibles </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% else %}
        <p>No hay Laboratorios</p>
    {% endif %}  
    <div class="text-left mt-3">
    <br><a href="{% url 'laboratorio:agregar_laboratorio' %}" class="btn btn-light btn">Crear Laboratorio</a><br>
    <br><a href="{% url 'index' %}" class="btn btn-link">Ir al Inicio</a>
    </div>
</div>
{% endblock %}    

practica_final_orm_django/config/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %}Principal{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">Productos Farmacéuticos</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'laboratorio:listar_laboratorios' %}">Laboratorios</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    
    <!--Contenido Principal-->
    <div class="container mt-4">
        
        {% block content %} {% endblock %}
    </div>
        
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'js/scripts.js'%}"></script>
</body>
</html>

practica_final_orm_django/config/templates/index.html
{% extends 'base.html'%}

{% block title %} Página Principal {% endblock %}

{% block content%}

<header class="text-center">
    <h1>PÁGINA PRINCIPAL</h1>
</header>

<div class="jumbotron bg-light p-5 rounded mt-4">
    <div class="row"> 
        <div class="col-lg-8 col-md-10 col-sm-12 mx-auto text-center">
            <h2 class="display-4">Bienvenido</h2>
            
            <hr class="my-4">
            
        </div>
    </div>
</div>
   
{% endblock %}